# Generated by Django 5.0.1 on 2024-02-06 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rating_rating_user_alter_rating_rated_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='rating_user',
        ),
    ]
