# Generated by Django 5.0.1 on 2024-02-03 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_event_creater'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(default=2, help_text='A short description of the event', max_length=125),
            preserve_default=False,
        ),
    ]
