# Generated by Django 5.0.1 on 2024-02-03 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_event_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='creater',
            new_name='creator',
        ),
    ]
