# Generated by Django 5.0.1 on 2024-02-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_event_options_event_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
