# Generated by Django 5.0.1 on 2024-02-03 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_creater_event_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collide',
            name='rsvps',
        ),
        migrations.RemoveField(
            model_name='event',
            name='collides',
        ),
        migrations.AddField(
            model_name='collide',
            name='event',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main_app.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rsvp',
            name='collide',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main_app.collide'),
            preserve_default=False,
        ),
    ]
