# Generated by Django 5.0.1 on 2024-02-07 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_event_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.CharField(default='https://i.imgur.com/9h1LE28.png', max_length=250),
        ),
    ]
