# Generated by Django 5.0.1 on 2024-02-08 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_event_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
